<template>
  <svg viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
    <rect
      x="4"
      y="3"
      width="12"
      height="8"
      rx="1"
      stroke="currentColor"
      stroke-width="2"
    />
    <rect
      x="8"
      y="11"
      width="4"
      height="7"
      rx="1"
      stroke="currentColor"
      stroke-width="2"
    />
    <line
      x1="6"
      y1="18"
      x2="14"
      y2="18"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
    />
  </svg>
</template>
