<template>
  <svg viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
    <rect
      x="3"
      y="5"
      width="13"
      height="9"
      rx="1"
      stroke="currentColor"
      stroke-width="2"
    />
    <line
      x1="2"
      y1="17"
      x2="17"
      y2="17"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
    />
  </svg>
</template>
